using System.Collections.Concurrent;
using CountryService.Models;

namespace CountryService.Services;

public class CountryService : ICountryService
{
    private readonly ConcurrentDictionary<string, string> _countries;

    public CountryService()
    {
        _countries = new ConcurrentDictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        _countries.TryAdd("AF", "Afghanistan");
        _countries.TryAdd("AL", "Albania");
        _countries.TryAdd("DZ", "Algeria");
        _countries.TryAdd("AS", "American Samoa");
        _countries.TryAdd("AD", "Andorra");
        _countries.TryAdd("AO", "Angola");
        _countries.TryAdd("AI", "Anguilla");
        _countries.TryAdd("AQ", "Antarctica");
        _countries.TryAdd("AG", "Antigua and Barbuda");
        _countries.TryAdd("AR", "Argentina");
        _countries.TryAdd("AM", "Armenia");
        _countries.TryAdd("AW", "Aruba");
        _countries.TryAdd("AU", "Australia");
        _countries.TryAdd("AT", "Austria");
        _countries.TryAdd("AZ", "Azerbaijan");
        _countries.TryAdd("BS", "Bahamas");
        _countries.TryAdd("BH", "Bahrain");
        _countries.TryAdd("BD", "Bangladesh");
        _countries.TryAdd("BB", "Barbados");
        _countries.TryAdd("BY", "Belarus");
        _countries.TryAdd("BE", "Belgium");
        _countries.TryAdd("BZ", "Belize");
        _countries.TryAdd("BJ", "Benin");
        _countries.TryAdd("BM", "Bermuda");
        _countries.TryAdd("BT", "Bhutan");
        _countries.TryAdd("BO", "Bolivia");
        _countries.TryAdd("BA", "Bosnia and Herzegovina");
        _countries.TryAdd("BW", "Botswana");
        _countries.TryAdd("BR", "Brazil");
        _countries.TryAdd("IO", "British Indian Ocean Territory");
        _countries.TryAdd("BN", "Brunei Darussalam");
        _countries.TryAdd("BG", "Bulgaria");
        _countries.TryAdd("BF", "Burkina Faso");
        _countries.TryAdd("BI", "Burundi");
        _countries.TryAdd("KH", "Cambodia");
        _countries.TryAdd("CM", "Cameroon");
        _countries.TryAdd("CA", "Canada");
        _countries.TryAdd("CV", "Cape Verde");
        _countries.TryAdd("KY", "Cayman Islands");
        _countries.TryAdd("CF", "Central African Republic");
        _countries.TryAdd("TD", "Chad");
        _countries.TryAdd("CL", "Chile");
        _countries.TryAdd("CN", "China");
        _countries.TryAdd("CX", "Christmas Island");
        _countries.TryAdd("CC", "Cocos (Keeling) Islands");
        _countries.TryAdd("CO", "Colombia");
        _countries.TryAdd("KM", "Comoros");
        _countries.TryAdd("CG", "Congo");
        _countries.TryAdd("CD", "Congo, Democratic Republic");
        _countries.TryAdd("CK", "Cook Islands");
        _countries.TryAdd("CR", "Costa Rica");
        _countries.TryAdd("CI", "Côte d'Ivoire");
        _countries.TryAdd("HR", "Croatia");
        _countries.TryAdd("CU", "Cuba");
        _countries.TryAdd("CY", "Cyprus");
        _countries.TryAdd("CZ", "Czech Republic");
        _countries.TryAdd("DK", "Denmark");
        _countries.TryAdd("DJ", "Djibouti");
        _countries.TryAdd("DM", "Dominica");
        _countries.TryAdd("DO", "Dominican Republic");
        _countries.TryAdd("EC", "Ecuador");
        _countries.TryAdd("EG", "Egypt");
        _countries.TryAdd("SV", "El Salvador");
        _countries.TryAdd("GQ", "Equatorial Guinea");
        _countries.TryAdd("ER", "Eritrea");
        _countries.TryAdd("EE", "Estonia");
        _countries.TryAdd("SZ", "Eswatini");
        _countries.TryAdd("ET", "Ethiopia");
        _countries.TryAdd("FK", "Falkland Islands");
        _countries.TryAdd("FO", "Faroe Islands");
        _countries.TryAdd("FJ", "Fiji");
        _countries.TryAdd("FI", "Finland");
        _countries.TryAdd("FR", "France");
        _countries.TryAdd("GF", "French Guiana");
        _countries.TryAdd("PF", "French Polynesia");
        _countries.TryAdd("GA", "Gabon");
        _countries.TryAdd("GM", "Gambia");
        _countries.TryAdd("GE", "Georgia");
        _countries.TryAdd("DE", "Germany");
        _countries.TryAdd("GH", "Ghana");
        _countries.TryAdd("GI", "Gibraltar");
        _countries.TryAdd("GR", "Greece");
        _countries.TryAdd("GL", "Greenland");
        _countries.TryAdd("GD", "Grenada");
        _countries.TryAdd("GP", "Guadeloupe");
        _countries.TryAdd("GU", "Guam");
        _countries.TryAdd("GT", "Guatemala");
        _countries.TryAdd("GG", "Guernsey");
        _countries.TryAdd("GN", "Guinea");
        _countries.TryAdd("GW", "Guinea-Bissau");
        _countries.TryAdd("GY", "Guyana");
        _countries.TryAdd("HT", "Haiti");
        _countries.TryAdd("VA", "Holy See");
        _countries.TryAdd("HN", "Honduras");
        _countries.TryAdd("HK", "Hong Kong");
        _countries.TryAdd("HU", "Hungary");
        _countries.TryAdd("IS", "Iceland");
        _countries.TryAdd("IN", "India");
        _countries.TryAdd("ID", "Indonesia");
        _countries.TryAdd("IR", "Iran");
        _countries.TryAdd("IQ", "Iraq");
        _countries.TryAdd("IE", "Ireland");
        _countries.TryAdd("IM", "Isle of Man");
        _countries.TryAdd("IL", "Israel");
        _countries.TryAdd("IT", "Italy");
        _countries.TryAdd("JM", "Jamaica");
        _countries.TryAdd("JP", "Japan");
        _countries.TryAdd("JE", "Jersey");
        _countries.TryAdd("JO", "Jordan");
        _countries.TryAdd("KZ", "Kazakhstan");
        _countries.TryAdd("KE", "Kenya");
        _countries.TryAdd("KI", "Kiribati");
        _countries.TryAdd("KP", "North Korea");
        _countries.TryAdd("KR", "South Korea");
        _countries.TryAdd("KW", "Kuwait");
        _countries.TryAdd("KG", "Kyrgyzstan");
        _countries.TryAdd("LA", "Lao People's Democratic Republic");
        _countries.TryAdd("LV", "Latvia");
        _countries.TryAdd("LB", "Lebanon");
        _countries.TryAdd("LS", "Lesotho");
        _countries.TryAdd("LR", "Liberia");
        _countries.TryAdd("LY", "Libya");
        _countries.TryAdd("LI", "Liechtenstein");
        _countries.TryAdd("LT", "Lithuania");
        _countries.TryAdd("LU", "Luxembourg");
        _countries.TryAdd("MO", "Macao");
        _countries.TryAdd("MG", "Madagascar");
        _countries.TryAdd("MW", "Malawi");
        _countries.TryAdd("MY", "Malaysia");
        _countries.TryAdd("MV", "Maldives");
        _countries.TryAdd("ML", "Mali");
        _countries.TryAdd("MT", "Malta");
        _countries.TryAdd("MH", "Marshall Islands");
        _countries.TryAdd("MQ", "Martinique");
        _countries.TryAdd("MR", "Mauritania");
        _countries.TryAdd("MU", "Mauritius");
        _countries.TryAdd("YT", "Mayotte");
        _countries.TryAdd("MX", "Mexico");
        _countries.TryAdd("FM", "Micronesia");
        _countries.TryAdd("MD", "Moldova");
        _countries.TryAdd("MC", "Monaco");
        _countries.TryAdd("MN", "Mongolia");
        _countries.TryAdd("ME", "Montenegro");
        _countries.TryAdd("MS", "Montserrat");
        _countries.TryAdd("MA", "Morocco");
        _countries.TryAdd("MZ", "Mozambique");
        _countries.TryAdd("MM", "Myanmar");
        _countries.TryAdd("NA", "Namibia");
        _countries.TryAdd("NR", "Nauru");
        _countries.TryAdd("NP", "Nepal");
        _countries.TryAdd("NL", "Netherlands");
        _countries.TryAdd("NC", "New Caledonia");
        _countries.TryAdd("NZ", "New Zealand");
        _countries.TryAdd("NI", "Nicaragua");
        _countries.TryAdd("NE", "Niger");
        _countries.TryAdd("NG", "Nigeria");
        _countries.TryAdd("NU", "Niue");
        _countries.TryAdd("NF", "Norfolk Island");
        _countries.TryAdd("MK", "North Macedonia");
        _countries.TryAdd("MP", "Northern Mariana Islands");
        _countries.TryAdd("NO", "Norway");
        _countries.TryAdd("OM", "Oman");
        _countries.TryAdd("PK", "Pakistan");
        _countries.TryAdd("PW", "Palau");
        _countries.TryAdd("PS", "Palestine, State of");
        _countries.TryAdd("PA", "Panama");
        _countries.TryAdd("PG", "Papua New Guinea");
        _countries.TryAdd("PY", "Paraguay");
        _countries.TryAdd("PE", "Peru");
        _countries.TryAdd("PH", "Philippines");
        _countries.TryAdd("PL", "Poland");
        _countries.TryAdd("PT", "Portugal");
        _countries.TryAdd("PR", "Puerto Rico");
        _countries.TryAdd("QA", "Qatar");
        _countries.TryAdd("RE", "Réunion");
        _countries.TryAdd("RO", "Romania");
        _countries.TryAdd("RU", "Russian Federation");
        _countries.TryAdd("RW", "Rwanda");
        _countries.TryAdd("BL", "Saint Barthélemy");
        _countries.TryAdd("SH", "Saint Helena");
        _countries.TryAdd("KN", "Saint Kitts and Nevis");
        _countries.TryAdd("LC", "Saint Lucia");
        _countries.TryAdd("MF", "Saint Martin");
        _countries.TryAdd("PM", "Saint Pierre and Miquelon");
        _countries.TryAdd("VC", "Saint Vincent and the Grenadines");
        _countries.TryAdd("WS", "Samoa");
        _countries.TryAdd("SM", "San Marino");
        _countries.TryAdd("ST", "Sao Tome and Principe");
        _countries.TryAdd("SA", "Saudi Arabia");
        _countries.TryAdd("SN", "Senegal");
        _countries.TryAdd("RS", "Serbia");
        _countries.TryAdd("SC", "Seychelles");
        _countries.TryAdd("SL", "Sierra Leone");
        _countries.TryAdd("SG", "Singapore");
        _countries.TryAdd("SX", "Sint Maarten");
        _countries.TryAdd("SK", "Slovakia");
        _countries.TryAdd("SI", "Slovenia");
        _countries.TryAdd("SB", "Solomon Islands");
        _countries.TryAdd("SO", "Somalia");
        _countries.TryAdd("ZA", "South Africa");
        _countries.TryAdd("GS", "South Georgia and the South Sandwich Islands");
        _countries.TryAdd("SS", "South Sudan");
        _countries.TryAdd("ES", "Spain");
        _countries.TryAdd("LK", "Sri Lanka");
        _countries.TryAdd("SD", "Sudan");
        _countries.TryAdd("SR", "Suriname");
        _countries.TryAdd("SJ", "Svalbard and Jan Mayen");
        _countries.TryAdd("SE", "Sweden");
        _countries.TryAdd("CH", "Switzerland");
        _countries.TryAdd("SY", "Syrian Arab Republic");
        _countries.TryAdd("TW", "Taiwan");
        _countries.TryAdd("TJ", "Tajikistan");
        _countries.TryAdd("TZ", "Tanzania");
        _countries.TryAdd("TH", "Thailand");
        _countries.TryAdd("TL", "Timor-Leste");
        _countries.TryAdd("TG", "Togo");
        _countries.TryAdd("TK", "Tokelau");
        _countries.TryAdd("TO", "Tonga");
        _countries.TryAdd("TT", "Trinidad and Tobago");
        _countries.TryAdd("TN", "Tunisia");
        _countries.TryAdd("TR", "Turkey");
        _countries.TryAdd("TM", "Turkmenistan");
        _countries.TryAdd("TC", "Turks and Caicos Islands");
        _countries.TryAdd("TV", "Tuvalu");
        _countries.TryAdd("UG", "Uganda");
        _countries.TryAdd("UA", "Ukraine");
        _countries.TryAdd("AE", "United Arab Emirates");
        _countries.TryAdd("GB", "United Kingdom");
        _countries.TryAdd("US", "United States");
        _countries.TryAdd("UM", "United States Minor Outlying Islands");
        _countries.TryAdd("UY", "Uruguay");
        _countries.TryAdd("UZ", "Uzbekistan");
        _countries.TryAdd("VU", "Vanuatu");
        _countries.TryAdd("VE", "Venezuela");
        _countries.TryAdd("VN", "Vietnam");
        _countries.TryAdd("VG", "Virgin Islands, British");
        _countries.TryAdd("VI", "Virgin Islands, U.S.");
        _countries.TryAdd("WF", "Wallis and Futuna");
        _countries.TryAdd("EH", "Western Sahara");
        _countries.TryAdd("YE", "Yemen");
        _countries.TryAdd("ZM", "Zambia");
        _countries.TryAdd("ZW", "Zimbabwe");
    }

    public IEnumerable<Country> GetAllCountries()
    {
        return _countries
            .Select(kv => new Country(kv.Key.ToUpperInvariant(), kv.Value))
            .OrderBy(c => c.Name);
    }

    public CountryAddResult AddCountry(Country country)
    {
        if (string.IsNullOrWhiteSpace(country.Code) || string.IsNullOrWhiteSpace(country.Name))
            return CountryAddResult.Invalid;

        if (!_countries.TryAdd(country.Code.Trim(), country.Name.Trim()))
            return CountryAddResult.Duplicate;

        return CountryAddResult.Success;
    }
}